# Generated by Django 2.2.1 on 2019-06-24 09:36

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('rating', models.IntegerField()),
                ('date', models.DateTimeField(max_length=100)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('password1', models.CharField(max_length=100)),
                ('password2', models.CharField(max_length=100)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', multiselectfield.db.fields.MultiSelectField(choices=[('M', 'Male'), ('F', 'Female')], max_length=30)),
                ('No_of_marriages', multiselectfield.db.fields.MultiSelectField(choices=[('1', 'one'), ('2', 'two'), ('3', 'three')], max_length=20)),
                ('Expectation1', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kat', 'Katrina Kaif'), ('deepu', 'Deepika Padukone'), ('sunney', 'Sunney Leoni')], max_length=50, null=True)),
                ('Expectation2', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('sallu', 'Salman Khan'), ('sahid', 'Shahid Kapoor'), ('ranveer', 'Ranveer Singh')], max_length=50, null=True)),
                ('alcoholic_status', multiselectfield.db.fields.MultiSelectField(choices=[('no', 'No alcoholic'), ('yes', 'Only on weekends'), ('yes', 'Occasionally')], max_length=50)),
                ('more_info', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
